swagger: '2.0'
info:
  version: 0.0.1
  title: NLMG API
  description: New Lion HighSchool Sports App API.
host: localhost:8280
basePath: /v1
# basePath: /api
schemes:
  - http
  - https
produces:
  - application/json
securityDefinitions:
  seasonLinkInternal:
    type: oauth2
    description: >
      Exchanges an email/password for an access_token. Only
      to be used by the SeasonLink app.
    # name: access_token
    # in: header
    flow: password
    tokenUrl: http://localhost:8280/v1/login
    scopes: {}
paths:
  /me:
    get:
      summary: Returns the current logged in user.
      operationId: me
      security:
        - seasonLinkInternal: []
      responses:
        200:
          description: User summary
          schema:
            $ref: SuccessEnvelope
            properties:
              meta:
                type: object
              response:
                description: User Model
                $ref: User
        default:
          description: The standard error envelope.
          schema:
            $ref: ErrorEnvelope

  /login:
    post:
      summary: Exchange a username (i.e. email) and password for an access token.
      description: >
        Logging in will return just the access_token in the
        response when successful. Follow up with a call to `/me` if you
        want to get the user details.
      parameters:
        - name: email
          in: formData
          description: >
            The user's email. SeasonLink does not have usernames,
            but the OAuth2 spec requires this to be the param name.
          required: true
          type: string
        - name: password
          in: formData
          description: The user's password.
          required: true
          type: string
      responses:
        200:
          description: Returns the access_token
          schema:
            $ref: SuccessEnvelope
            properties:
              meta:
                type: object
              response:
                properties:
                  access_token:
                    type: string
        default:
          description: The standard error envelope.
          schema:
            $ref: ErrorEnvelope

  /signup:
    post:
      summary: Creates a new user account.
      description: >
        Creating a new user will return an object containing the user
        and the access_token in the response when successful.
      parameters:
        - name: firstName
          in: formData
          description: First name of the user.
          required: false
          type: string
        - name: lastName
          in: formData
          description: Last name of the user.
          required: false
          type: string
        - name: password
          in: formData
          description: The user's password.
          required: true
          type: string
        - name: email
          in: formData
          description: The user's email address.
          required: true
          type: string
      responses:
        200:
          description: Returns the access_token for the new user.
          schema:
            $ref: SuccessEnvelope
            properties:
              meta:
                type: object
              response:
                properties:
                  user:
                    $ref: User
                  access_token:
                    type: string
        default:
          description: The standard error envelope.
          schema:
            $ref: ErrorEnvelope

  /users:
    get:
      description: Returns array of Users.
      summary: Retrieve Users.
      operationId: getUsersList
      responses:
        200:
          description: List all users.
          schema:
            $ref: SuccessEnvelope
            properties:
              meta:
                type: object
              response:
                type: array
                items:
                  $ref: User
        default:
          description: The standard error envelope.
          schema:
            $ref: ErrorEnvelope

  /users/{userId}:
    get:
      parameters:
      - name: userId
        in: path
        description: the Id of the User
        required: true
        type: string
      description: Returns a User based on supplied Id.
      summary: Retrieve a User Object.
      operationId: getUserById
      responses:
        200:
          description:  Return a User.
          schema:
            $ref: SuccessEnvelope
            properties:
              meta:
                type: object
              response:
                $ref: User
        default:
          description: The standard error envelope.
          schema:
            $ref: ErrorEnvelope

  /teams:
    get:
      description: Returns array of Teams.
      summary: Retrieve Teams.
      operationId: getTeamsList
      responses:
        200:
          description: List all Teams.
          schema:
            type: array
            items:
              $ref: SuccessEnvelope
              properties:
                meta:
                  type: object
                response:
                  $ref: Team
        default:
          description: The standard error envelope.
          schema:
            $ref: ErrorEnvelope

  # /teams/search:

  # /teams/follow/:teamId?:

  # /teams/unfollow/:teamId?:

  # /teams/:teamId:

  # /schools:

  # /schools/search:

  # /schools/:schoolId:

  # /events:

  # /events/search:

  # /events/:eventId:

  # /messages:

  # /messages/search:

  # /messages/:messageId:

definitions:
  ErrorEnvelope:
    description: API error envelope response
    required:
      - meta
    properties:
      meta:
        description: meta data of the error envelope
        type: object
        required:
          - code
          - errorType
          - errorDetail
        properties:
          code:
            type: integer
            format: int32
          errorType:
            description: "Additional information about what went wrong, intended for the developer."
            type: string
          errorDetail:
            description: A localized string intended for the client to display back to the user directly.
            type: string

  SuccessEnvelope:
    description: API success envelope response
    required:
      - meta
      - response
    properties:
      meta:
        description: meta data of the sucess envelope
        type: object
        required:
          - code
        properties:
          code:
            type: integer
            format: int32
      response:
        description: response data of successful API call
        type: object

  User:
    description: User Object
    required:
      - email
      - password
    properties:
      username:
        description: Username of User
        type: string
      firstName:
        description: First name of User
        type: string
      lastName:
        description: Last name of User
        type: string
      email:
        description: Email address of User
        type: string
      password:
        description: Salted passward hash of User
        type: string
      accounts:
        description: List of accounts associated with User
        type: array
        items:
          type: object
      devices:
        description: List of devices associated with User
        type: array
        items:
          type: object
      roles:
        description: List of roles associated with User
        type: array
        items:
          type: object
      createdTime:
        description: Date of User model creation
        type: string
        format: date-time
      lastVisitTime:
        description: Date of User's last visit
        type: string
        format: date-time
      birthday:
        description: Date of User's birthday
        type: string
        format: date-time
      followedTeams:
        description: List of Mongodb ObjectIds of teams followed
        type: array
        items:
          $ref:  ObjectId
      preferences:
        description: List of User preference objects
        type: array
        items:
          type: object

  ObjectId:
    description: Mongodb ObjectId definition
    properties:
      id:
        description: Id attribute of ObjectId
        type: string
